
import { useState, useEffect } from 'react';
import { Item, ItemCategory } from '@/types';
import { useLocalStorage } from '@/pages/items/hooks/useLocalStorage';

export const useProductManagement = () => {
  // Use local storage to retrieve saved products
  const [savedProducts, setSavedProducts] = useLocalStorage<Item[]>('seller-products', []);
  const [products, setProducts] = useState<Item[]>([]);
  const [activeFilter, setActiveFilter] = useState<string | null>(null);
  
  // Initialize with sample products if no saved products
  useEffect(() => {
    const sampleProducts: Item[] = [
      {
        id: '1',
        name: 'Organic Bananas',
        description: 'Bundle of organic bananas, slightly ripened',
        category: 'food',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2023-06-01',
        createdAt: '2023-05-15',
        updatedAt: '2023-05-15',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 20,
        originalPrice: 399.99,
        currentPrice: 299.99,
        dynamicPricingEnabled: true,
      },
      {
        id: '2',
        name: 'T-shirts Pack',
        description: 'Pack of 5 plain t-shirts, various sizes',
        category: 'clothing',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2024-05-15',
        createdAt: '2023-05-10',
        updatedAt: '2023-05-10',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 10,
        originalPrice: 3499.00,
        currentPrice: 2499.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '3',
        name: 'Wireless Earbuds',
        description: 'Bluetooth 5.0 wireless earbuds with noise cancellation',
        category: 'electronics',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2025-01-01',
        createdAt: '2023-05-08',
        updatedAt: '2023-05-08',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 15,
        originalPrice: 5999.00,
        currentPrice: 4499.00,
        dynamicPricingEnabled: true,
      },
      {
        id: '4',
        name: 'Organic Honey',
        description: 'Pure organic honey from mountain flowers',
        category: 'food',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2024-12-01',
        createdAt: '2023-05-05',
        updatedAt: '2023-05-05',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 30,
        originalPrice: 899.00,
        currentPrice: 799.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '5',
        name: 'Yoga Mat',
        description: 'Non-slip eco-friendly yoga mat',
        category: 'fitness',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-05-01',
        updatedAt: '2023-05-01',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 25,
        originalPrice: 1299.00,
        currentPrice: 999.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '6',
        name: 'Reusable Water Bottle',
        description: 'Stainless steel insulated water bottle',
        category: 'household',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-04-28',
        updatedAt: '2023-04-28',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 40,
        originalPrice: 899.00,
        currentPrice: 699.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '7',
        name: 'Bamboo Cutlery Set',
        description: 'Eco-friendly bamboo cutlery travel set',
        category: 'household',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-04-25',
        updatedAt: '2023-04-25',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 35,
        originalPrice: 599.00,
        currentPrice: 499.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '8',
        name: 'Organic Coffee Beans',
        description: 'Premium organic coffee beans, medium roast',
        category: 'food',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2024-06-15',
        createdAt: '2023-04-20',
        updatedAt: '2023-04-20',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 50,
        originalPrice: 799.00,
        currentPrice: 699.00,
        dynamicPricingEnabled: true,
      },
      {
        id: '9',
        name: 'LED Desk Lamp',
        description: 'Adjustable LED desk lamp with 5 brightness levels',
        category: 'electronics',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-04-15',
        updatedAt: '2023-04-15',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 20,
        originalPrice: 1999.00,
        currentPrice: 1499.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '10',
        name: 'Recycled Paper Notebooks',
        description: 'Pack of 3 notebooks made from recycled paper',
        category: 'stationery',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-04-10',
        updatedAt: '2023-04-10',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 45,
        originalPrice: 499.00,
        currentPrice: 399.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '11',
        name: 'Bamboo Toothbrushes',
        description: 'Set of 4 biodegradable bamboo toothbrushes',
        category: 'household',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-04-05',
        updatedAt: '2023-04-05',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 60,
        originalPrice: 399.00,
        currentPrice: 299.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '12',
        name: 'Organic Spices Set',
        description: 'Collection of 6 organic cooking spices',
        category: 'food',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2024-10-01',
        createdAt: '2023-04-01',
        updatedAt: '2023-04-01',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 25,
        originalPrice: 999.00,
        currentPrice: 899.00,
        dynamicPricingEnabled: true,
      },
      {
        id: '13',
        name: 'Portable Solar Charger',
        description: 'Compact solar power bank for mobile devices',
        category: 'electronics',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-03-25',
        updatedAt: '2023-03-25',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 15,
        originalPrice: 3499.00,
        currentPrice: 2999.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '14',
        name: 'Linen Kitchen Towels',
        description: 'Set of 3 natural linen kitchen towels',
        category: 'household',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-03-20',
        updatedAt: '2023-03-20',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 30,
        originalPrice: 799.00,
        currentPrice: 599.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '15',
        name: 'Organic Green Tea',
        description: '100g of premium organic green tea leaves',
        category: 'food',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2024-08-15',
        createdAt: '2023-03-15',
        updatedAt: '2023-03-15',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 40,
        originalPrice: 499.00,
        currentPrice: 399.00,
        dynamicPricingEnabled: true,
      },
      {
        id: '16',
        name: 'Recycled Fabric Tote Bag',
        description: 'Sturdy tote bag made from recycled materials',
        category: 'clothing',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-03-10',
        updatedAt: '2023-03-10',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 50,
        originalPrice: 699.00,
        currentPrice: 599.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '17',
        name: 'Bluetooth Fitness Tracker',
        description: 'Waterproof fitness tracker with heart rate monitor',
        category: 'electronics',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-03-05',
        updatedAt: '2023-03-05',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 15,
        originalPrice: 4999.00,
        currentPrice: 3999.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '18',
        name: 'Organic Dark Chocolate',
        description: 'Fair trade organic dark chocolate bars, pack of 3',
        category: 'food',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2024-04-01',
        createdAt: '2023-03-01',
        updatedAt: '2023-03-01',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 35,
        originalPrice: 599.00,
        currentPrice: 499.00,
        dynamicPricingEnabled: true,
      },
      {
        id: '19',
        name: 'Handmade Ceramic Mug',
        description: 'Artisanal ceramic coffee mug, 350ml',
        category: 'household',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: null,
        createdAt: '2023-02-25',
        updatedAt: '2023-02-25',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 20,
        originalPrice: 899.00,
        currentPrice: 799.00,
        dynamicPricingEnabled: false,
      },
      {
        id: '20',
        name: 'Natural Bath Bombs',
        description: 'Set of 6 natural ingredient bath bombs',
        category: 'beauty',
        imageUrl: 'https://via.placeholder.com/150',
        expiryDate: '2024-02-20',
        createdAt: '2023-02-20',
        updatedAt: '2023-02-20',
        status: 'available',
        userId: 'seller123',
        userName: 'Demo Business',
        userPhoto: null,
        location: {
          address: '123 Main St',
          lat: 40.7128,
          lng: -74.006,
        },
        quantity: 25,
        originalPrice: 999.00,
        currentPrice: 799.00,
        dynamicPricingEnabled: false,
      }
    ];
    
    // Combine sample products with saved products
    const allProducts = [...sampleProducts];
    if (savedProducts && savedProducts.length > 0) {
      savedProducts.forEach(product => {
        // Add only if not already in the list
        if (!allProducts.some(p => p.id === product.id)) {
          allProducts.push(product);
        }
      });
    }
    
    setProducts(allProducts);
  }, [savedProducts]);

  const handleFilterByCategory = (category: ItemCategory | null) => {
    if (category === activeFilter) {
      setActiveFilter(null); // Clear filter if clicking the active one
    } else {
      setActiveFilter(category);
    }
  };
  
  // Get filtered products
  const filteredProducts = activeFilter 
    ? products.filter(p => p.category === activeFilter) 
    : products;

  return {
    products,
    filteredProducts,
    activeFilter,
    handleFilterByCategory
  };
};
