
import { Item } from '@/types';

export const generateMockSellerProducts = (): Item[] => {
  return [
    {
      id: 'prod-1',
      name: 'Organic Tomatoes',
      description: 'Fresh organic tomatoes from local farms',
      category: 'food',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1582284540020-8acbe03f4924?q=80&w=300',
      quantity: 50,
      currentPrice: 5.99,
      originalPrice: 7.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-2',
      name: 'Cotton T-shirts (5-pack)',
      description: 'Pack of 5 cotton t-shirts, assorted colors',
      category: 'clothing',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=300',
      quantity: 25,
      currentPrice: 1299.00,
      originalPrice: 1599.00,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-3',
      name: 'Bluetooth Headphones',
      description: 'Wireless Bluetooth headphones with noise cancellation',
      category: 'electronics',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1578319439584-104c94d37305?q=80&w=300',
      quantity: 10,
      currentPrice: 2499.00,
      originalPrice: 2999.00,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-4',
      name: 'Organic Bananas',
      description: 'Fresh organic bananas from sustainable farms',
      category: 'food',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1543218024-57a70143c369?q=80&w=300',
      quantity: 100,
      currentPrice: 3.49,
      originalPrice: 4.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-5',
      name: 'Reusable Shopping Bags',
      description: 'Eco-friendly reusable shopping bags, pack of 3',
      category: 'household',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1591824438708-ce405f36ba3d?q=80&w=300',
      quantity: 75,
      currentPrice: 9.99,
      originalPrice: 12.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-6',
      name: 'Bamboo Toothbrushes',
      description: 'Biodegradable bamboo toothbrushes, pack of 4',
      category: 'household',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1607853827120-6851a99b5b91?q=80&w=300',
      quantity: 120,
      currentPrice: 7.99,
      originalPrice: 9.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-7',
      name: 'Natural Almond Milk',
      description: 'Fresh almond milk with no preservatives, 1L',
      category: 'food',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1615744455875-7ad33653e8c4?q=80&w=300',
      quantity: 40,
      currentPrice: 4.49,
      originalPrice: 5.49,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-8',
      name: 'Yoga Mat',
      description: 'Premium non-slip eco-friendly yoga mat',
      category: 'sports',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?q=80&w=300',
      quantity: 25,
      currentPrice: 24.99,
      originalPrice: 29.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-9',
      name: 'Stainless Steel Water Bottle',
      description: 'Vacuum insulated stainless steel water bottle, 750ml',
      category: 'household',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=300',
      quantity: 60,
      currentPrice: 19.99,
      originalPrice: 24.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-10',
      name: 'Organic Coffee Beans',
      description: 'Fair trade organic coffee beans, 500g',
      category: 'food',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?q=80&w=300',
      quantity: 50,
      currentPrice: 14.99,
      originalPrice: 17.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-11',
      name: 'Recycled Paper Notebooks',
      description: 'Set of 3 notebooks made from recycled paper',
      category: 'other',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?q=80&w=300',
      quantity: 85,
      currentPrice: 12.99,
      originalPrice: 15.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-12',
      name: 'Organic Honey',
      description: 'Pure organic wildflower honey, 500g',
      category: 'food',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?q=80&w=300',
      quantity: 40,
      currentPrice: 9.99,
      originalPrice: 12.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-13',
      name: 'Handmade Soap Set',
      description: 'Set of 4 natural handmade soaps',
      category: 'beauty',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?q=80&w=300',
      quantity: 30,
      currentPrice: 16.99,
      originalPrice: 19.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-14',
      name: 'Bamboo Cutting Board',
      description: 'Durable bamboo cutting board, eco-friendly',
      category: 'household',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1594136976553-38728ce9aa57?q=80&w=300',
      quantity: 35,
      currentPrice: 21.99,
      originalPrice: 26.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-15',
      name: 'Solar Powered Charger',
      description: 'Portable solar power bank for mobile devices',
      category: 'electronics',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1557674751-3ea33e3cbc41?q=80&w=300',
      quantity: 20,
      currentPrice: 49.99,
      originalPrice: 59.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-16',
      name: 'Organic Herb Garden Kit',
      description: 'Grow your own herbs with this starter kit',
      category: 'other',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1590931825202-bad96785427c?q=80&w=300',
      quantity: 15,
      currentPrice: 29.99,
      originalPrice: 34.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-17',
      name: 'Natural Beeswax Candles',
      description: 'Set of 3 natural beeswax candles',
      category: 'household',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=300',
      quantity: 40,
      currentPrice: 18.99,
      originalPrice: 22.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: null,
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-18',
      name: 'Coconut Oil Hair Mask',
      description: 'Natural hair treatment with coconut oil, 250ml',
      category: 'beauty',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=300',
      quantity: 25,
      currentPrice: 15.99,
      originalPrice: 19.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-19',
      name: 'Organic Quinoa',
      description: 'Premium organic quinoa, 500g',
      category: 'food',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1612257999517-f27e593d09b1?q=80&w=300',
      quantity: 60,
      currentPrice: 7.99,
      originalPrice: 9.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    },
    {
      id: 'prod-20',
      name: 'Eco-Friendly Laundry Detergent',
      description: 'Biodegradable laundry detergent, 2L',
      category: 'household',
      status: 'available',
      imageUrl: 'https://images.unsplash.com/photo-1585834377603-804f6f5c91b5?q=80&w=300',
      quantity: 45,
      currentPrice: 13.99,
      originalPrice: 16.99,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      expiryDate: new Date(Date.now() + 240 * 24 * 60 * 60 * 1000).toISOString(),
      userId: 'seller-123',
      userName: 'John Seller',
      userPhoto: null,
      location: {
        lat: 28.6139,
        lng: 77.2090,
        address: '123 Market St, Delhi, India',
      }
    }
  ];
};
