// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krupkuoyijlnamjnheau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtydXBrdW95aWpsbmFtam5oZWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjM5NjUsImV4cCI6MjA2MzAzOTk2NX0.OpRydxoSazCbstdRBBaTLQMbAZHCkMTIvpGZslq8T9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);