
import { useState } from 'react';
import { Order } from '@/types';

export const useMockOrders = () => {
  // Mock data that would normally come from an API
  const [orders, setOrders] = useState<Order[]>([
    {
      id: 'ORD001',
      buyerId: 'buyer123',
      buyerName: 'John Doe',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '1', 
          name: 'Organic Bananas', 
          quantity: 2, 
          price: 299.99, 
          productId: 'product1', 
          orderId: 'ORD001',
          imageUrl: undefined,
        },
      ],
      status: 'pending',
      paymentStatus: 'paid',
      totalAmount: 599.98,
      createdAt: '2023-05-20T10:30:00',
      updatedAt: '2023-05-20T10:30:00',
      shippingAddress: '123 Main St, City, Country',
    },
    {
      id: 'ORD002',
      buyerId: 'buyer456',
      buyerName: 'Jane Smith',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '2', 
          name: 'T-shirts Pack', 
          quantity: 1, 
          price: 2499.00, 
          productId: 'product2', 
          orderId: 'ORD002',
          imageUrl: undefined,
        },
      ],
      status: 'shipped',
      paymentStatus: 'paid',
      totalAmount: 2499.00,
      createdAt: '2023-05-19T14:15:00',
      updatedAt: '2023-05-19T14:15:00',
      shippingAddress: '456 Oak St, City, Country',
    },
    {
      id: 'ORD003',
      buyerId: 'buyer789',
      buyerName: 'Alex Johnson',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '3', 
          name: 'Wireless Earbuds', 
          quantity: 1, 
          price: 1999.00, 
          productId: 'product3', 
          orderId: 'ORD003',
          imageUrl: undefined,
        },
      ],
      status: 'out-for-delivery',
      paymentStatus: 'paid',
      totalAmount: 1999.00,
      createdAt: '2023-05-18T09:30:00',
      updatedAt: '2023-05-18T09:30:00',
      shippingAddress: '789 Pine St, City, Country',
    },
    {
      id: 'ORD004',
      buyerId: 'buyer234',
      buyerName: 'Emily Wilson',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '4', 
          name: 'Organic Honey', 
          quantity: 3, 
          price: 799.00, 
          productId: 'product4', 
          orderId: 'ORD004',
          imageUrl: undefined,
        },
        { 
          id: '5', 
          name: 'Organic Coffee Beans', 
          quantity: 2, 
          price: 699.00, 
          productId: 'product5', 
          orderId: 'ORD004',
          imageUrl: undefined,
        }
      ],
      status: 'delivered',
      paymentStatus: 'paid',
      totalAmount: 3793.00,
      createdAt: '2023-05-15T11:45:00',
      updatedAt: '2023-05-17T09:20:00',
      shippingAddress: '567 Elm St, City, Country',
    },
    {
      id: 'ORD005',
      buyerId: 'buyer345',
      buyerName: 'Michael Brown',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '6', 
          name: 'Yoga Mat', 
          quantity: 1, 
          price: 999.00, 
          productId: 'product6', 
          orderId: 'ORD005',
          imageUrl: undefined,
        },
      ],
      status: 'processing',
      paymentStatus: 'paid',
      totalAmount: 999.00,
      createdAt: '2023-05-21T08:30:00',
      updatedAt: '2023-05-21T08:35:00',
      shippingAddress: '890 Cherry Ave, City, Country',
    },
    {
      id: 'ORD006',
      buyerId: 'buyer567',
      buyerName: 'Sarah Thompson',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '7', 
          name: 'Reusable Water Bottle', 
          quantity: 2, 
          price: 699.00, 
          productId: 'product7', 
          orderId: 'ORD006',
          imageUrl: undefined,
        },
        { 
          id: '8', 
          name: 'Bamboo Cutlery Set', 
          quantity: 1, 
          price: 499.00, 
          productId: 'product8', 
          orderId: 'ORD006',
          imageUrl: undefined,
        }
      ],
      status: 'pending',
      paymentStatus: 'pending',
      totalAmount: 1897.00,
      createdAt: '2023-05-22T13:15:00',
      updatedAt: '2023-05-22T13:15:00',
      shippingAddress: '123 Maple Dr, City, Country',
    },
    {
      id: 'ORD007',
      buyerId: 'buyer678',
      buyerName: 'Robert Green',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '9', 
          name: 'LED Desk Lamp', 
          quantity: 1, 
          price: 1499.00, 
          productId: 'product9', 
          orderId: 'ORD007',
          imageUrl: undefined,
        },
      ],
      status: 'cancelled',
      paymentStatus: 'refunded',
      totalAmount: 1499.00,
      createdAt: '2023-05-16T16:20:00',
      updatedAt: '2023-05-17T10:45:00',
      shippingAddress: '456 Birch St, City, Country',
    },
    {
      id: 'ORD008',
      buyerId: 'buyer789',
      buyerName: 'Alex Johnson',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '10', 
          name: 'Recycled Paper Notebooks', 
          quantity: 3, 
          price: 399.00, 
          productId: 'product10', 
          orderId: 'ORD008',
          imageUrl: undefined,
        },
      ],
      status: 'shipped',
      paymentStatus: 'paid',
      totalAmount: 1197.00,
      createdAt: '2023-05-19T09:10:00',
      updatedAt: '2023-05-20T11:25:00',
      shippingAddress: '789 Pine St, City, Country',
    },
    {
      id: 'ORD009',
      buyerId: 'buyer234',
      buyerName: 'Emily Wilson',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '11', 
          name: 'Bamboo Toothbrushes', 
          quantity: 2, 
          price: 299.00, 
          productId: 'product11', 
          orderId: 'ORD009',
          imageUrl: undefined,
        },
        { 
          id: '12', 
          name: 'Organic Spices Set', 
          quantity: 1, 
          price: 899.00, 
          productId: 'product12', 
          orderId: 'ORD009',
          imageUrl: undefined,
        }
      ],
      status: 'delivered',
      paymentStatus: 'paid',
      totalAmount: 1497.00,
      createdAt: '2023-05-14T14:50:00',
      updatedAt: '2023-05-16T13:20:00',
      shippingAddress: '567 Elm St, City, Country',
    },
    {
      id: 'ORD010',
      buyerId: 'buyer456',
      buyerName: 'Jane Smith',
      sellerId: 'seller123',
      userId: 'seller123',
      items: [
        { 
          id: '13', 
          name: 'Portable Solar Charger', 
          quantity: 1, 
          price: 2999.00, 
          productId: 'product13', 
          orderId: 'ORD010',
          imageUrl: undefined,
        },
      ],
      status: 'out-for-delivery',
      paymentStatus: 'paid',
      totalAmount: 2999.00,
      createdAt: '2023-05-20T15:40:00',
      updatedAt: '2023-05-21T09:15:00',
      shippingAddress: '456 Oak St, City, Country',
    },
  ]);

  return {
    orders,
    setOrders
  };
};
